// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleApp.DBContext;

#nullable disable

namespace _.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260130061148_AddedNewColumnsToAccountsTable")]
    partial class AddedNewColumnsToAccountsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SampleApp.Models.Accounts.AccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedBy")
                        .HasColumnType("int")
                        .HasColumnName("added_by");

                    b.Property<DateOnly?>("DateAdded")
                        .HasColumnType("date")
                        .HasColumnName("date_added");

                    b.Property<DateOnly?>("DateRemoved")
                        .HasColumnType("date")
                        .HasColumnName("date_removed");

                    b.Property<bool?>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnName("is_removed");

                    b.Property<int?>("RemovedBy")
                        .HasColumnType("int")
                        .HasColumnName("removed_by");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AddedBy");

                    b.HasIndex("RemovedBy");

                    b.ToTable("account_types");
                });

            modelBuilder.Entity("SampleApp.Models.Auth.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateCreated")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasColumnName("is_approved");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<int>("UserType")
                        .HasColumnType("int")
                        .HasColumnName("user_type");

                    b.Property<DateOnly?>("UserTypeDateUpdated")
                        .HasColumnType("date")
                        .HasColumnName("user_type_date_updated");

                    b.Property<long?>("UserTypeUpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("user_type_updated_by");

                    b.HasKey("Id");

                    b.HasIndex("UserType");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("SampleApp.Models.Auth.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit")
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("SampleApp.Models.Accounts.AccountType", b =>
                {
                    b.HasOne("SampleApp.Models.Auth.Account", "AddedByAccount")
                        .WithMany("AddedAccountTypes")
                        .HasForeignKey("AddedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SampleApp.Models.Auth.Account", "RemovedByAccount")
                        .WithMany("RemovedAccountTypes")
                        .HasForeignKey("RemovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AddedByAccount");

                    b.Navigation("RemovedByAccount");
                });

            modelBuilder.Entity("SampleApp.Models.Auth.Account", b =>
                {
                    b.HasOne("SampleApp.Models.Accounts.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("UserType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountType");
                });

            modelBuilder.Entity("SampleApp.Models.Auth.RefreshToken", b =>
                {
                    b.HasOne("SampleApp.Models.Auth.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SampleApp.Models.Auth.Account", b =>
                {
                    b.Navigation("AddedAccountTypes");

                    b.Navigation("RemovedAccountTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
